docker tag pulse-monitoring_analyser yuragranovsky/pulse-monitoring_analyser
docker tag pulse-monitoring_avg-reducer yuragranovsky/pulse-monitoring_avg-reducer
docker tag pulse-monitoring_avg-values-back-office yuragranovsky/pulse-monitoring_avg-values-back-office
docker tag pulse-monitoring_avg-values-populator yuragranovsky/pulse-monitoring_avg-values-populator
docker tag pulse-monitoring_doctor-patient-data-provider yuragranovsky/pulse-monitoring_doctor-patient-data-provider
docker tag pulse-monitoring_jumps-mail-notifier yuragranovsky/pulse-monitoring_jumps-mail-notifier
docker tag pulse-monitoring_monitoring-config-server yuragranovsky/pulse-monitoring_monitoring-config-server
docker tag pulse-monitoring_security-gateway yuragranovsky/pulse-monitoring_security-gateway
docker tag pulse-monitoring_visits-back-office yuragranovsky/pulse-monitoring_visits-back-office